### ISSUE TITLE
DataPortal Complete method assumes there is always an __dataportaltimer in the ClientContext

### ISSUE THREAD

**Issue by rfcdejong** [MarimerLLC/csla#1790] opened 2020-08-28 09:11 UTC
**Describe the bug**
During runtime sometimes we get the error at DataPortal.cs in Csla.Net4.6
The code assumes there is always a __dataportaltimer in the ClientContext, but somehow that is not the case. I don't know why. Perhaps it is a known issue and there is a workaround?
The ClientContext has 0 items

The strange thing is that I see the Initialize method is being called in the dataportal.Fetch method, but during the method I guess something happens with the ClientContext. I have yet to debug it and hope I can resolve it somehow...

**Version and Platform**
CSLA version: 5.3.0.0
OS: Windows
Platform: WPF

**Code that Fails**
DataPortal.cs line 648 in method internal void Complete(InterceptArgs e)
var startTime = (DateTimeOffset)ApplicationContext.ClientContext["__dataportaltimer"];

**Stack Trace or Exception Detail**
System.NullReferenceException: 'Object reference not set to an instance of an object.'
System.Collections.Specialized.HybridDictionary.this[object].get returned null.

called by DataPorta.Fetch line 305:
        Complete(new InterceptArgs { ObjectType = objectType, Parameter = criteria, Result = result, Operation = DataPortalOperations.Fetch, IsSync = isSync });

called by Csla.Web.Mvc5 HttpPortal.Fetch line 106:
        var dpr = await prtl.Fetch(objectType, criteria, context, true);

**Comment by rfcdejong** [comment] 2020-08-28 09:24
A possible solution would be to pass along the DataPortalContext parameter to initialize and complete, but I don't have an answer yet to why it happens. SetContext might go wrong in some cases, maybe when ExecutionLocation is Client or when the call is inside a new Thread. Digging in deeper for now..

**Comment by rfcdejong** [comment] 2020-08-28 10:03
I managed to set a breakpoint on the specific place just before the exception is being thrown.
It goes though the Csla.DataPortalClient.LocalProxy.Fetch.AnonymousMethod__0() line 81
There the DataPortalContext context parameter is assigned, but the properties (and fields) are nearly all null..

ClientContext = null;
ClientCulture = null;
IsRemotePortal = false;
Principal = null;
TransactionalType = Csla.TransactionalTypes.Manual;

LocalicalExecutionLocation is Client
FlowSynchronizationContext is false
SynchronizationContext.Current is null

Perhaps this is a thread related issue

Gotta dig deeper

**Comment by rfcdejong** [comment] 2020-08-28 10:28
Any information about the ApplicationContext.WebContextManager ? It is null on my side. All I know is that when it is null and using the LocalProxy / isRemotePortal = false that the above exception in this issue is a fact.

On the DataPortalContext.cs line 125 the DataPortalContext constructor doesn't set the _clientContext and _globalContext when the WebContextManager is null.

Please throw a more friendly exception or allow the WebContextManager to be null.

I'm gonna take a lunch break :)

**Comment by rfcdejong** [comment] 2020-08-28 11:26
Looking at it I don't know why WebcontextManager is null

I'll just modify the code locally and always assign _clientContext and _globalContext even though WebContextManager is null.

**Comment by rfcdejong** [comment] 2020-08-28 14:34
This seems related
https://github.com/MarimerLLC/csla/issues/1417#issuecomment-568868706

**Comment by rockfordlhotka** [comment] 2020-08-28 17:52
You might be encountering the issue discussed here: https://github.com/MarimerLLC/csla/discussions/1750

Try setting the `CslaFlowSynchronizationContext` config value to change how CSLA passes state to background threads.

**Comment by rockfordlhotka** [comment] 2020-09-11 14:24
@rfcdejong did the `CslaFlowSynchronizationContext` setting help?

**Comment by rfcdejong** [comment] 2020-09-11 15:24
yes and no, but it is too early to say.. it could be the reason for another issue

setting it to true:
 - it sets the client context so the exception is no being thrown
 - the HttpContext is not being passed on from DataPortalController to ObjectFactory

![image](https://user-images.githubusercontent.com/2665653/92942402-c56ced80-f451-11ea-908f-ae215d7add4a.png)

So I don't know if I can set it to true yet. I have to resolve the other issue first

I was too busy adjusting our code since breaking changes for BeginCreate and BeginFetch, not that they are Obsolete, but that we use it without criteria. In the past it would resolve the factory without criteria, now it assumes it has csla EmptyCriteria. I think this will be one of the last times we can upgrade to a new version of csla without spending too much time. Over 1400 BeginFetch which should become await FetchAsync

**Comment by rockfordlhotka** [comment] 2020-09-11 15:34
HttpContext will generally NOT be available in the server-side data portal, especially in .NET Core.

**Comment by rfcdejong** [comment] 2020-09-11 15:42
It used to work, that code used to modify Application Insights telemetry based on the operation name, so we can inspect request performance and calls.

We are still on .NET 4.6.2, in .NET Core I would use the HttpContextAccessor.

I have either to hook into somewhere between this, in the Controller the HttpContext is available
In the ObjectFactory the HttpContext is gone. I don't want to pass along or make it injectable.

![image](https://user-images.githubusercontent.com/2665653/92945531-af612c00-f455-11ea-84c2-0a8f3d0cfec3.png)


More of an chicken and egg issue :(
It would had been nice if I could access the DataPortalContext for the current request inside a Application Insights TelemetryInitializer.

**Comment by rockfordlhotka** [comment] 2020-09-11 15:46
In .NET Core you should inject a factory, from which you get the HttpContext. I'm in a meeting and don't remember the factory type to inject, but that's the new model.

**Comment by rfcdejong** [comment] 2020-09-11 15:47
> In .NET Core you should inject a factory, from which you get the HttpContext. I'm in a meeting and don't remember the factory type to inject, but that's the new model.

We are not using .NET Core sadly.

**Comment by rfcdejong** [comment] 2020-09-11 15:48
> **Update** oh - duh - you call it out in your post!! 😳

:)

**Comment by rfcdejong** [comment] 2020-09-11 15:56
I think I have three possible solutions to look at:

1. Somehow make the current telemetry accessible for the Factory
2. Somehow make the dataportal context accessible for the TelemetryInitializer.
3. Deserialize the Request content inside the controller myself before calling base.Post (will probl. have a performance impact)

We used to use nr 1 using the HttpContext, but I don't know why that no longer works...

**Comment by ajohnstone-ks** [comment] 2020-09-11 17:54
Hi @rockfordlhotka we are also seeing this issue, on Csla 5.3.1 running under .Net Framework 4.8.  We also have the `CslaFlowSynchronizationContext` to `true` in our `web.config`.  

It seems to happen most frequently if on the server side data portal call we call another BO's data portal method, for example a command object which returns server BOs (to reduce the number of server calls)

**Comment by rfcdejong** [comment] 2020-09-11 18:49
Beside this NullReference exception (which should not even be thrown in the first place)

How would you support Application Insights telemetry for RemoteDataPortal calls? From Client to Server only. To see for which business object a call is made thru the dataportal?

**Comment by rockfordlhotka** [comment] 2020-09-11 18:51
@rfcdejong  Can you ask that as a post in Discussions to avoid side-tracking this issue?

**Comment by ajohnstone-ks** [comment] 2020-09-11 18:52
The changes to LocalProxy also match what I'm seeing, in that if I change the BO being fetched server side to use just Fetch it still happens as the BO's DataPortal_Fetch is still async.  In other cases just changing the FetchAsync to Fetch fixes it, but most of our DP_F methods are still sync.

**Comment by rfcdejong** [comment] 2020-09-11 19:03
> @rfcdejong Can you ask that as a post in Discussions to avoid side-tracking this issue?

done https://github.com/MarimerLLC/csla/discussions/1809

**Comment by rockfordlhotka** [comment] 2020-10-04 18:22
I am finally getting to dig into this. 

#1400 has a good explanation about why we changed the code to stop using a custom task scheduler, and that reasoning remains valid.

#1400 also discusses how having CSLA flow HttpContext isn't in scope - I can't really coerce .NET to flow HttpContext, that's Microsoft's job.

There does remain the issue where the __dataportaltimer is always assumed to exist in ClientContext, so that's what I'm working to resolve at this point.

**Comment by rfcdejong** [comment] 2020-10-05 12:38
@rockfordlhotka this is a workaround to prevent the exception from being thrown but the real problem resides in the use of AsyncLocal in ASP.NET MVC combined (with .NET Framework 4.6.2)

there is something wrong with the ApplicationContextManager. It uses AsyncLocal and sometimes, I really haven't figured out when, the dictionary is null. Runtime we ran into errors that the ClientContext is missing (on our side the selected tenantId) values and things on the server-side are very bad..

Looking at https://github.com/MiniProfiler/dotnet/issues/173 I found that AsyncLocal is not to be trusted
Also look at https://github.com/aspnet/AspNetKatana/issues/31#issuecomment-285216648

**Comment by rockfordlhotka** [comment] 2020-10-05 14:07
For scenarios like you describe you should be able to change the application context manager to use TLS. We actually put the "old" [ApplicationContextManagerTls](https://github.com/MarimerLLC/csla/blob/master/Source/Csla.Shared/Core/ApplicationContextManagerTls.cs) manager into the framework to make it easy to use.

Just configure this at startup and you won't be using AsyncLocal at all.

**Comment by rockfordlhotka** [comment] 2020-10-05 15:05
GlobalContext absolutely doesn't flow bi-directionally in async scenarios - never has and probably never will, as that's way too complex! 😄

**Comment by rfcdejong** [comment] 2020-10-05 15:18
FYI using the ApplicationContextManagerTls the ClientContext is available again in my scenario, no need to pass along the ClientContext thru the dataportals over and over. It would perhaps be better to ensure the ClientContext is always passed along, but for now I will use the named slots as we want to bring out a new version of our software soon with the new csla and this was blocking the release.. and I didn't want to revert all my commits regarding new CSLA version either.

**Comment by rockfordlhotka** [comment] 2020-10-22 16:28
I spent some time working on this yesterday and today.

I am going to close this issue, because `ApplicationContextManagerTls` is a viable workaround/solution for the scenario.

This _may be fixed in v6_ because I plan to do some pretty major rework to allow various things like context and config and `ApplicationContext` to flow differently than they do now. Right now they are basically per-thread globals, which makes some DI-based and parallel testing scenarios problematic.

Now to be honest, I don't know for sure that we can escape per-thread globals, but that's what I'm hoping to do 😄

**Closed by rockfordlhotka** 2020-10-22 16:28 UTC
Labels: area/asp.net, kind/bug

**Comment by rockfordlhotka** [comment] 2021-01-05 19:06
@rfcdejong It has been a long time, but I finally have some time to try and figure this out.

The problem is, that I've created an ASP.NET 4.8 project, and `ApplicationContext.ClientContext` is flowing through to a local data portal with no issue.

In this test code I'm setting a value into `ClientContext`, calling the data portal, and in the `Fetch` method I'm getting that context value and putting it into a property so it flows back to the caller.

Put a breakpoint right after the `Index` method calls the data portal, and the new `PersonEdit` object has the correct `Name` and `Context` property values.

So I'm failing to understand the nature of the problem.

```c#
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Csla;

namespace CslaContextFlow.Controllers
{
  public class HomeController : Controller
  {
    public async Task<ActionResult> Index()
    {
      ApplicationContext.ClientContext["test"] = "test";
      var obj = await DataPortal.FetchAsync<PersonEdit>("abc");
      return View();
    }

    public ActionResult About()
    {
      ViewBag.Message = "Your application description page.";

      return View();
    }

    public ActionResult Contact()
    {
      ViewBag.Message = "Your contact page.";

      return View();
    }
  }

  [Serializable]
  public class PersonEdit : BusinessBase<PersonEdit>
  {
    public static readonly PropertyInfo<string> NameProperty = RegisterProperty<string>(nameof(Name));
    public string Name
    {
      get => GetProperty(NameProperty);
      set => SetProperty(NameProperty, value);
    }

    public static readonly PropertyInfo<string> ContextProperty = RegisterProperty<string>(nameof(Context));
    public string Context
    {
      get => GetProperty(ContextProperty);
      set => SetProperty(ContextProperty, value);
    }

    [RunLocal]
    [Create]
    private void Create()
    {
      using (BypassPropertyChecks)
      {
        Name = "<new>";
      }
    }

    [Fetch]
    private void Fetch(string name)
    {
      using (BypassPropertyChecks)
      {
        Name = name;
        Context = ApplicationContext.ClientContext["test"].ToString();
      }
    }
  }
}
```
