### ISSUE TITLE
Templates vsix doesn't build

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/csla#753] opened 2017-08-04 12:00 UTC
The templates vsix project needs some attention. I'll have a go at fixing it up.

**Comment by dazinator** [comment] 2017-08-04 12:18
Might widen this issue to cover creating a vsix for vs2017.
I think to add support for vs2017, and keep support for all other vs versions, we will now need two vsix's as impossible to support all in a single vsix.

**Comment by rockfordlhotka** [comment] 2017-08-09 23:45
As you work on this it might resolve #752?

**Comment by rockfordlhotka** [comment] 2019-06-26 06:10
Duplicate of #752

**Closed by rockfordlhotka** 2019-06-26 06:10 UTC
Labels: help wanted, technical debt
