### ISSUE TITLE
ConnectionManager may not be releasing connections under stress

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#377] opened 2015-06-09 20:58 UTC
http://forums.lhotka.net/forums/p/12896/58322.aspx#58322

> Yes, I'm fairly confident it's ConnectionManager.  The issue seems to be, ironically, that the connections are not being properly returned to the pool.  We already have the pool size at 500, from the 100 default.
> 
> Last year, when we were still on Csla 3.7 we tried to do a wholesale conversion from manually new'ing up SqlConnection to using ConnectionManager.  Quite literally a find/replace.  It worked well for a few days, but then we got these hangs.  We did see some errors logged about timeouts trying to get a connection from the pool.  We reverted the changes and redeployed, and things went back to normal.  The timing of the hang seems to be as our load increases (when our East coast customers begin coming online through when our West coast customers do).
> 
> We had hoped that our planned Csla 4.5 update would have some changes that would resolve this, and after we did the update we've been slowly converting things to use CM as we touch the BOs for other reasons since upgraded about six months ago (and are on the most current version).
> 
> We have a bunch of background threads (our SaaS app is a WinForms client) pooling for things at various times.  This last release we did some refactoring and added one more, and moved something that was not previously in the DB to the DB; both these threads basically are new hits to the DB and we did them with ConnectionManager.  The hangs returned, and I did find more errors indicating timeouts getting a connection from the pool.  I changed the server code used by these two threads to just new up the connection, and our hang has gone away again, so far.  We'll see, we just did the hotfix on Sunday so I want to give it a few more days, but based on our previous experience I don't think the issue will return.
> 
> So, that's all I have, and of course we've only seen this in production, so we haven't had a lot of opportunity to investigate as we have to get the system back online.  The issue does seem to only manifest during our busy times, which are mornings and especially weekends (Saturday / Sunday), so I suspect load has something to do with it.

**Comment by richardbartley** [comment] 2015-07-01 10:01
So if there are no connections in the pool available, the request gets queued and then timesout.  Would catching that error and calling System.Data.SqlClient.SqlConnection.ClearAllPools() help here, followed by a retry opening connection strategy?

**Comment by richardbartley** [comment] 2015-07-01 10:07
Or the SqlConnection.ClearPool(<yourSqlConnection>) to just clear a specific connection.

**Comment by rockfordlhotka** [comment] 2015-07-08 18:41
ConnectionManager implements its release strategy based on `using` blocks. If you have nested `using` blocks (or none) then the only way it will release connections is when garbage collected.

I bring this up, because the OP mentions that this happens under heavy load times, making it sound a lot like the releases aren't occurring except by the GC.

**Comment by jonnybee** [comment] 2015-08-03 05:23
Unless we are really sure that the OP has coded and used ConnectionManager properly and there is no logical flaw in the code we should close this issue. 
There is not enough information to pursue this issue as is.

**Comment by WileE577** [comment] 2015-08-08 01:28
I believe I'm having this same issue and I think I've found the cause in ConnectionManager:

The connection open and close occur within a global lock. This means that if the open takes a long time (default is 15 seconds if the connection pool is maxed out), no other connection can be open or closed during that time. 

A simple example would be if you had a Max Pool Size=1 and two requests. You would see something like this:
* Request 1 - Opens a connection with ConnectionManager and makes a database call
* Request 2 - ConnectionManager locks and attempts to open a connection. The open waits for an available connection.
* Request 1 - completes its database call and calls connection manager dispose (end of using block)
* Request 1 - ConnectionManager calls DeRef and waits for the lock to clear from request 2
* Request 2 - The connection open times out after 15 seconds, throws an exception and frees the lock
* Request 1 - DeRef is now able to lock and call the connection dispose to close the connection. This request will take a little over 15 seconds total but succeed.

With more requests and a higher Max Pool Size, its more complicated to see what is going on. I discovered the issue when I saw that I had database calls that took a short time between open and calling ConnectionManager dispose (milliseconds) but the dispose took 15 seconds.  

I'm using a slightly modified version of CSLA 3.8.4 but I've also replicated this in 4.5.701.
I have created a console app that can replicate by running x number of threads that use a connection manager with a Max Pool Size of x-1. The last thread to attempt to open a connection times out after 15 and the other threads then are able to close the connection.

I modified the 3.8.4 ConnectionManager code to replace both instances of `lock (_lock)` with `lock (ApplicationContext.LocalContext.SyncRoot)` so that it only locks for the threads that have the same LocalContext. When I run against that version, the first request is able to close the connection and the second can then open a connection.

Perhaps you have a better solution to locking to avoid blocking threads that would never use the same ConnectionManager.

**Comment by jonnybee** [comment] 2015-08-14 06:08
Have you tried to move the _connection.Open to after the lock has been released?

**Comment by WileE577** [comment] 2015-08-14 07:40
Yes, that is what I tried first. But, if the open fails, it leaves the ConnectionManager in the LocalContext with a ref count of 1. It would have to have a try/catch that removed it from LocalContext. Even so, it wouldn't guarantee that another thread hadn't gotten the reference with ref count 1 and attempted to use it.

**Comment by jonnybee** [comment] 2015-08-14 07:57
Hmm, the entire concept of ConnectionManager is to only share it within the running thread - without having to pass the connection as a parameter to other methods (like child / grandchild objects).

**Comment by jonnybee** [comment] 2015-08-14 09:17
How about if you change to this code where there is no lock on Connection.Open()?

    public static ConnectionManager GetManager(string database, bool isDatabaseName, string label)
    {
      if (isDatabaseName)
      {
        var connection = ConfigurationManager.ConnectionStrings[database];
        if (connection == null)
          throw new ConfigurationErrorsException(String.Format(Resources.DatabaseNameNotFound, database));

        var conn = ConfigurationManager.ConnectionStrings[database].ConnectionString;
        if (string.IsNullOrEmpty(conn))
          throw new ConfigurationErrorsException(String.Format(Resources.DatabaseNameNotFound, database));
        database = conn;
      }
	  
	  ConnectionManager mgr = null;
      lock (_lock)
      {
        var ctxName = GetContextName(database, label);
        if (ApplicationContext.LocalContext.Contains(ctxName))
        {
          mgr = (ConnectionManager)(ApplicationContext.LocalContext[ctxName]);
        }
        else
        {
          mgr = new ConnectionManager(database, label);
        }
      }
	  
	  // no locks on Open as this may take time to establish 
	  mgr.Connection.Open(); 
	  
      lock (_lock)
      {
        ApplicationContext.LocalContext[ctxName] = mgr;
        mgr.AddRef();
        return mgr;
	  }
    }
	
	private ConnectionManager(string connectionString, string label)
    {
      _label = label;
      _connectionString = connectionString;

      string provider = ConfigurationManager.AppSettings["dbProvider"];
      if (string.IsNullOrEmpty(provider))
        provider = "System.Data.SqlClient";

      DbProviderFactory factory = DbProviderFactories.GetFactory(provider);

      // open connection
      _connection = factory.CreateConnection();
      _connection.ConnectionString = connectionString;
    }

**Comment by rockfordlhotka** [comment] 2015-08-14 16:16
I like where you are going with this @jonnybee. Perhaps this is a slight refinement?

```csharp
  ConnectionManager mgr = null;
  var ctxName = GetContextName(database, label);
  var isNew = false;
  lock (_lock)
  {
    if (ApplicationContext.LocalContext.Contains(ctxName))
    {
      mgr = (ConnectionManager)(ApplicationContext.LocalContext[ctxName]);
    }
    else
    {
      mgr = new ConnectionManager(database, label);
      ApplicationContext.LocalContext[ctxName] = mgr;
      isNew = true;
    }
    mgr.AddRef();
  }

  // no locks on Open as this may take time to establish 
  if (isNew)
    mgr.Connection.Open(); 
  return mgr;
```

**Comment by jonnybee** [comment] 2015-08-14 17:23
There is one more issue: 

1. If Connection.Open() fails method will throw an exception, the variable will not be assigned nor will  Dispose() be called on the object - hence - it should not be added to the local context and AddRef() should not be called.

Maybe this is an even better solution:
    public static ConnectionManager GetManager(string database, bool isDatabaseName, string label)
	{
	  	if (isDatabaseName)
	  	{
		    var connection = ConfigurationManager.ConnectionStrings[database];
		    if (connection == null)
		      throw new ConfigurationErrorsException(String.Format(Resources.DatabaseNameNotFound, database));
	
		    var conn = ConfigurationManager.ConnectionStrings[database].ConnectionString;
		    if (string.IsNullOrEmpty(conn))
		      throw new ConfigurationErrorsException(String.Format(Resources.DatabaseNameNotFound, database));
		    database = conn;
	  	}

	  ConnectionManager mgr = null;
          var ctxName = GetContextName(database, label);
	  lock (_lock)
	  {
	    if (ApplicationContext.LocalContext.Contains(ctxName))
	    {
	    	mgr = (ConnectionManager)(ApplicationContext.LocalContext[ctxName]);
		    mgr.AddRef();
		    return mgr;
	    }
	  }
	  
	  // this method will always return a new object and does no need a lock 
      mgr = new ConnectionManager(database, label);
      // but lock before we add to LocalContex 
	  lock (_lock)
	  {
	    ApplicationContext.LocalContext[ctxName] = mgr;
	    mgr.AddRef();
	    return mgr;
	  }
	}

	private ConnectionManager(string connectionString, string label)
	{
	  _label = label;
	  _connectionString = connectionString;
	
	  string provider = ConfigurationManager.AppSettings["dbProvider"];
	  if (string.IsNullOrEmpty(provider))
	    provider = "System.Data.SqlClient";
	
	  DbProviderFactory factory = DbProviderFactories.GetFactory(provider);
	
	  // open connection
	  _connection = factory.CreateConnection();
	  _connection.ConnectionString = connectionString;
	  _connection.Open();
	}

**Comment by WileE577** [comment] 2015-08-14 18:19
// this method will always return a new object and does no need a lock 
  mgr = new ConnectionManager(database, label);
  // but lock before we add to LocalContex 
  lock (_lock)
  {
    ApplicationContext.LocalContext[ctxName] = mgr;
    mgr.AddRef();
    return mgr;
  }

If two threads get here, assuming both succeed, there will be two connections. One would replace the other in LocalContext and the other would never be disposed. Also, ref count would be 2.

There needs to be something that stops another thread from attempting to open a connection.

**Comment by jonnybee** [comment] 2015-08-15 05:56
LocalContext is stored in a named DataSlot on Thread.CurrentThread. It will be different LocalContexts for different threads!

**Comment by rockfordlhotka** [comment] 2015-08-16 03:43
I'm actually trying to remember why I put the lock statements in the code to start with...

**Comment by SergeyBarskiy** [comment] 2015-08-16 15:19
I think the only time locks are necessary is when there is a Parallel.ForEach (or other thread spooling construct) in a web app, and each "thread" creates its own connection manager.  In my opinion, removing locks has a small possibility of breaking apps, but really small.  Break would involve connection leaking.  Pretty unlikely in my opinion.  On the other hand, the same code exists in other managers, like DB context manager.

**Comment by rockfordlhotka** [comment] 2015-08-16 15:34
Ahh, thank you Sergey, it is because in ASP.NET LocalContext is maintained in HttpContext and so is shared across threads (potentially) as you say.

So yes, there are cases where multiple threads could try to access LocalContext.

However, the lock protection needs to exist for protecting the LocalContext collection, not the connection or manager object. So I think that does mean we can try to put more logic outside the lock as long as LocalContext collection access (Contains, Add, etc.) is protected within the lock.

**Comment by SergeyBarskiy** [comment] 2015-08-16 15:50
It may also be worth considering switching to ConcurrentDictionary on .NET side for all XXXContext classes.  This way all locking code can be removed, scrunching the code down to LocalContext.AddOrUpdate('key", ()=> new XXXManager());  mgr = LocalContext.TryGet(), of (mgr != null) mgr.Conn.Open();  I feel it could be made far simpler by removing Conn.Open altogether from all other managers because it is not really needed for DbContextManager.  Hope this makes sense.

**Comment by jonnybee** [comment] 2015-08-19 06:01
Changing the dictionary type requires more code to map to DataPortalContext (which must be a Dictionary<string, object>) and I think it could get "messy" in the ContextManager implementations. 

Also - remember that 

    var ContextDictionary = concurrentDictionary.ToDictionary(kvp => kvp.Key, kvp => kvp.Value, dict.Comparer);

is not a threadsafe method. 

> However, members accessed through one of the interfaces the current collections implement, including extension methods, are not guaranteed to be thread safe and may need to be synchronized by the caller.

See: https://msdn.microsoft.com/en-us/library/system.collections.concurrent(v=vs.110).aspx 

I'd rather just keep the context as-is and make the necessary changes to ConnectionManager classes.

**Comment by rockfordlhotka** [comment] 2015-10-23 14:56
This conversation died down and I lost track of it - did anyone having the issue try the proposed solutions? And did they work?

**Comment by rockfordlhotka** [comment] 2015-11-03 00:15
Second call - does anyone have either a repro or a fix?

**Comment by WileE577** [comment] 2015-11-03 05:38
I have a way to reproduce in a console app. This is not a real world app, obviously, but I've seen the same result with a app that was maxing out the connection pool. The app had other issues causing the maxing out of the pool which have since been solved. The connection manager issue was making the actual app issue worse because it delays the dispose.
```
using System;
using System.Data.SqlClient;
using System.Diagnostics;
using Csla.Data;

namespace xpCslaCtxMgr
{
    class Program
    {
        const string connString = "Data Source=SERVER;Initial Catalog=DB;Integrated Security=True;Max Pool Size=1;Connect Timeout=5";

        static void Main(string[] args)
        {
            Trace.WriteLine("Program 1");
            try
            {
                DateTime st1 = DateTime.Now;
                DateTime st2;
                using (var ctx = ConnectionManager<SqlConnection>.GetManager(connString, false))
                {
                    Trace.WriteLine("Connection 1: Opened");
                    var t = new System.Threading.Thread(OtherThreadConection);
                    t.Start();
                    System.Threading.Thread.Sleep(1000); //Wait 1 second for other thread to start and open connection
                    st2 = DateTime.Now;
                    ctx.Dispose();
                }
                var time2 = DateTime.Now.Subtract(st2);
                var time1 = DateTime.Now.Subtract(st1);
                Trace.WriteLine($"Connection 1: Connection opened/closed in {time1.TotalMilliseconds:#,##0} MSs - Close in {time2.TotalMilliseconds:#,##0} MSs");
            }
            catch (Exception ex)
            {
                Trace.WriteLine("Connection 1: Exception: " + ex.Message);
            }
        }

        static void OtherThreadConection()
        {
            try
            {
                Trace.WriteLine("Connection 2: Attempting to open...");
                DateTime st1 = DateTime.Now;
                using (var cn = new SqlConnection(connString))
                {
                    cn.Open();
                    Trace.WriteLine($"Connection 2: Opened in {DateTime.Now.Subtract(st1).TotalMilliseconds} MSs");
                }
                var time1 = DateTime.Now.Subtract(st1);
                Trace.WriteLine($"Connection 2: Connection opened/closed in {time1.TotalMilliseconds:#,##0} MSs");
            }
            catch (Exception ex)
            {
                Trace.WriteLine("Connection 2: Exception:" + ex.Message);
            }
        }
    }
}
```
It uses a connection string with a max pool size of 1 and a connection timeout of 5. You need to provide a valid server and database name in the connection string.
In the output, you'll see that it takes Connection 1 more than 4 seconds to dispose and close the connection. Connection 1 is waiting on Connection 2 to fail before it can dispose.
If you replace the ConnectionManager with just a SqlConnection, Connection 1 disposes and closes in < 1 millisecond.

**Comment by jeffhtu** [comment] 2016-01-31 20:16
I'm perplexed by the serious nature of this bug and the lack of an "official" resolution to this issue. In my opinion, this bug has serious implication on scalability and performance of any mission critical applications. One would think there should have been a lot more buzz on this topic, but the lack of it makes me wonder if there are all but a few that actually uses CSLA in mission critical apps. Perhaps more alarming is the fact that this bug "should" have been caught in the first place by subjecting the framework with a comprehensive load testing. Are there no such test harnesses in place before new CSLA version is released? If not, are there any plans to do so in the future? For anyone looking into investing time and effort on adopting CSLA framework, this does not give us much confidence on going with CSLA, given the lack of urgency on an issue as fundamental as this.

**Comment by rockfordlhotka** [comment] 2016-02-01 17:14
I think a lot of the reason there's limited buzz is that the connection manager concept is entirely optional - it is a helper, not a core part of CSLA at all. And a _lot_ of people use EF or other technologies where connection manager doesn't apply at all. It is also the case that people using DI/IoC don't use connection manager, because they use injection to solve the shared connection issue.

Not to say that this isn't an issue, or that it shouldn't be solved - but it is to say that it isn't a core part of CSLA - it is a convenience on the periphery, that is easily ignored if it is problematic.

**Comment by NouvelleEcosse** [comment] 2016-05-03 19:56
Thanks, @jonnybee. Your code snippet made a big difference. We went from maxing out our pool to 10-20 sessions in our mission-critical application. @rockfordlhotka, do you anticipate an official fix for this bug?

**Comment by rockfordlhotka** [comment] 2017-08-10 00:04
I know this is from a long time back - what _is_ the suggested official fix? If you can put it in a PR that'd be extremely helpful!

**Comment by NouvelleEcosse** [comment] 2017-08-14 19:24
@rockfordlhotka, I don't know how to use git to put in a PR, but I am looking back to early 2016 and I see we did change the ConnectionManager as attached. I don't have a diff with your stock ConnectionManager, but it appears that I may have taken some code from @jonnybee and pasted it in there. I also have a comment in there to "test" something out, and neglected to remove this comment. But it has been tested since we use it. Haha! Perhaps you could take the code above from @WileE577 and use it to create a unit test for this class?

[csla_code.txt](https://github.com/MarimerLLC/csla/files/1223211/csla_code.txt)

**Comment by rockfordlhotka** [comment] 2018-04-10 21:19
It is pretty clear that the "fixed" code didn't really address the problem here, so I'm reopening the issue.

At the very least, `ConnectionManager` and `ConnectionManager<T>` have different implementations, and that's a problem.

But looking at the (more commonly used) `ConnectionManager<T>` code, it seems to me like there might be a race condition in the code.

**Comment by rockfordlhotka** [comment] 2018-04-10 21:31
Regarding the possible race condition, it is related to the updated `GetManager` code from earlier in this issue (from @jonnybee and @nouvelleecosse) (that is now in production):

```c#
      ConnectionManager<C> mgr = null;
      var ctxName = GetContextName(database, label);
      lock (_lock)
      {
        var cached = ApplicationContext.LocalContext.GetValueOrNull(ctxName);
        if (cached != null)
        {
          mgr = (ConnectionManager<C>)cached;
          mgr.AddRef();
        }
      }

      if (mgr == null)
      {
        mgr = new ConnectionManager<C>(database, label);
        lock (_lock)
        {
          ApplicationContext.LocalContext[ctxName] = mgr;
          mgr.AddRef();
        }
      }
      return mgr;
```

The problem I see here, is that 2 threads could get past the first block of code (past the first `lock`), neither having a connection. In that case, both threads could find `mgr == null` and thus both threads could create a new `ConnectionManager` and hence a new open connection.

Both threads would add the connection to `LocalContext`, though obviously whichever ran last would overwrite the first thread's object. And the ref count would be +2. One connection would be orphaned in memory, available only to the code running on that one thread. The other would be in `LocalContext`, and would be used by subsequent code/threads.

Or am I missing something here?

**Comment by tsf1** [comment] 2018-04-10 21:46
I'll add one observation from testing on my local machine within VS. I put in the following debug line inside of the DalManager constructor to observe what is happening:

```
        public DalManager()
        {
            ConnectionManager = ConnectionManager<SqlConnection>.GetManager("ConnectionString");

            if (ConnectionManager != null)
                System.Diagnostics.Debug.WriteLine(ConnectionManager.RefCount.ToString());
        }
```

Here are the results in the Output window when hitting a web page that calls to an business object (that in turn makes multiple calls to other objects - each with their own DP Fetch methods):

```
The thread 0x17dc has exited with code 259 (0x103).
4
4
27
6
12
6
4
15
24
15
The thread 0x4908 has exited with code 259 (0x103).
```

Even though over time the count goes back down, is it concerning that there are large ref counts (e.g. 27)? Does that actually equate to potentially 27 open connections? If so, then I could see the possibility of a handful of active users creating a problem with many open connections.

(In have some BO's that call other BOs while looking through a collection of objects, hence the large number of database calls. I suppose that brings up the question about whether that is good design. Even so, should it still handle it that way?)

Tim

**Comment by rockfordlhotka** [comment] 2018-04-10 21:48
RefCount is not the number of connections, it is the number of references to a specific connection. So what that number should mean is that there've been 27 calls to `GetManager` without corresponding calls (yet) to `Dispose`.

**Comment by rockfordlhotka** [comment] 2018-04-10 22:59
@tsf1 One thing your post does leave me wondering though.

You are printing the RefCount of the connection _when creating a DalManager_ - and you only create the DalManager in a root object right?

The first retrieval of the first DalManager should have been what creates the connection - so the ref count should be 0 to start with (or 1 I suppose). Somehow yours is 4?

What opened those other 3 connections? And what's keeping them open (i.e. didn't call `Dispose`)?

**Comment by tsf1** [comment] 2018-04-11 11:12
@rockfordlhotka sorry, that was just me picking a random spot in the output window. The count did start as normal.

**Comment by tsf1** [comment] 2018-04-11 11:27
One other thing to note: after I began to notice this issue getting worse, I took the advice I saw in various posts about using async calls to my factory methods so that, in theory, the IIS app pool worker processes would be freed up while waiting for database calls to return. I added async versions of nearly all of the factory methods in my BOs and began to call them from the MVC controllers. I almost think this has made things worse, but it's hard to say. Not sure what is the best practice there.

**Comment by tsf1** [comment] 2018-04-12 13:08
Update: I think I might have resolved the issue. Here's what I found and what I did to correct (I think - still preliminary):

My DalManager Dispose method was originally as follows:
```
        public void Dispose()
        {
            if (ConnectionManager != null)
            {
                    ConnectionManager.Dispose();
                    ConnectionManager = null;
                }
            }
        }
```
What I observed yesterday when looking at sysprocesses within SQL was that each user who visited the site created a bunch of open SQL connections. **The important observation here is that connections by one user were never reused by other users.** So connections would grow and grow as more people got on the site.

Following that observation, I changed my DalManager's Dispose method:
```
        public void Dispose()
        {
            if (ConnectionManager != null)
            {
                lock (_lock)
                {
                    if (ConnectionManager.RefCount == 1)
                    {
                        ConnectionManager.Connection.Close();
                    }

                    ConnectionManager.Dispose();
                    ConnectionManager = null;
                }
            }
        }
```
In other words, I explicitly started closing the connection if RefCount == 1 at the time of that call. I had to use a lock and also apply that to the DalManager constructor as well to ensure there wasn't a race condition (which happened a couple times before I included the lock):
```
        public DalManager()
        {
            lock (_lock)
            {
                ConnectionManager = ConnectionManager<SqlConnection>.GetManager("ConnectionString");
         }
```

Now that this change has been included, I can observe that SQL connections are being reused among active users.

The weird thing about this is that when looking at the underlying CSLA code for DalManager, it appears this same kind of logic was already being applied there, so I'm not sure where the hole is in it. But my changes seem to have dealt with the issue.

Tim

**Comment by rockfordlhotka** [comment] 2018-04-18 19:58
I wrote a test harness to try and figure out if there's an issue, and I surely can't find a case where the connection isn't closed - or at least where `Close` isn't called on the connection. I'm not testing against an actual SQL connection - I'm testing against a mock connection type so I can try "interesting" things.

So I'm at a loss as to why you are seeing the behavior described here.

**Comment by tsf1** [comment] 2018-04-18 20:05
Thanks, Rocky. Since my last update on this thread, the issue is gone. Closing the connection in my DalManager implementation made a difference though I'm not sure why. Perhaps something else in my code was at play in causing the issue. But I appreciate your help in working through it.

**Comment by rockfordlhotka** [comment] 2018-04-18 20:18
Glad to hear that @tsf1 !

For my reference, I'm leaving this issue open because the generic and non-generic `ConnectionManager` types differ in implementation, and only the generic one is correct, so this needs to be resolved.

**Comment by tfreitasleal** [comment] 2018-04-19 10:07
I feel a bit lost here.

Will the latest discussions result on a PR or is just a matter a changing the classes that use ConnectionManager?

In the later case, can I have a full reference implementation so I update the samples?

As you know, users tend to copy and paste samples. Updating ProjectTracker is the best way to advertize best practices.

**Comment by rockfordlhotka** [comment] 2018-04-19 16:25
@tfreitasleal I was entirely unable to replicate the issue @tsf1 was having, so I do not currently plan to change the generic `ConnectionManager` class.

I _do_ plan to update the non-generic `ConnectionManager` class, because it still has the old code that we know is wrong, and needs to be updated to match the generic version.

None of this should (to my knowledge) affect the samples.

**Closed** 2018-04-19 16:36 UTC
Labels: bug
