### ISSUE TITLE
Enable sourcelink

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/csla#1375] opened 2019-10-11 21:04 UTC
**Is your feature request related to a problem? Please describe.**
It would be useful to enable sourcelink.
Given an application with a package reference to a CSLA nuget package, source link allows stepping into the package source code which is extremely useful when trying to debug an issue happening somewhere inside CSLA.

The csla blazor sample also uses package references, and this would be useful to aid in debugging issues when working on that sample too.

**Describe the solution you'd like**
Enable source link.
The approach I have used to do this in my projects are:

1. Add this stuff to your [Directory.Build.props](https://github.com/dazinator/Dotnettency/blob/develop/src/Directory.Build.props)

That should now be enough to output *.snupkg packages when you build / publish.

2. Publish those symbol packages to nuget org. I do this via appveyor as seen here: https://github.com/dazinator/Dotnettency/blob/develop/appveyor.yml but I can't see a nuget deployment step inside your appveyor file so I assume your deployment to nuget is handled somewhere else.

Once thats done and symbol packages are being published, when we need to step into csla packages, its just a case of enabling source link is visual studio. 

**Describe alternatives you've considered**
Considered adding project references from the blazor sample to csla projects to debug into them, but this wont solve the problem for external applications / consumers.

**Additional context**

**Comment by dazinator** [comment] 2019-10-11 21:33
More info here: https://devblogs.microsoft.com/nuget/improved-package-debugging-experience-with-the-nuget-org-symbol-server/

**Comment by rockfordlhotka** [comment] 2019-10-12 04:43
This is a duplicate of #1188

**Closed by rockfordlhotka** 2019-10-12 04:43 UTC

**Comment by dazinator** [comment] 2019-10-12 06:35
An yes - apologies I missed that.
