### ISSUE TITLE
Can't Change ApplicationContext Properties via Configuration in .NET Core

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#800] opened 2017-11-29 17:23 UTC
I can't figure out a way to change properties like `AutoCloneOnUpdate`. Typically, in the .NET Framework, I set these values in app.config, but in .NET Core, that doesn't work. It also looks like the property doesn't even try to read anything from configuration in .NET Core, .NET Standard, etc.:

https://github.com/MarimerLLC/csla/blob/master/Source/Csla.Shared/ApplicationContext.cs#L464

There's also no public setter on this property so I can't change it in code.

I'm guessing other properties like `IsInRoleProvider` have the same issue. Some, like `PropertyChangedMode`, have a setter so at least that can be configured in code.

My suggestions would be:
* Add public setters for these properties
* Tie into how configuration works within .NET Core (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?tabs=basicconfiguration - I get that this article is for ASP.NET Core specifically but just referencing it)

I may also just be missing how to set up configuration files in .NET Core to make this all work - if I am, please let me know :). Even in that case, I feel that all of the properties on `ApplicationContext` should still be configurable in code.

**Comment by JohnWigger** [comment] 2017-11-30 21:17
I agree with your assessment on both points.  I have spent some time working with CSLA for ASP.NET Core 2.  In addition to my own project,  I am working on taking my lessons learned and putting them into to a version of the existing CslaMvc sample for ASP.NET Core 2.  The .NET Core configuration is a very fleshed out API but I focus on what I expect to happen in most scenarios.  That is, in a lowest common denominator approach, an application simply has one config and it is of the default json type.    One approach to dealing with this is to abstract access to AppSettings in a Config class that conditionally supports .NET Standard or the Full Framework approach.
` public static class Configurator
    {
#if NETSTANDARD || NETSTANDARD2_0
        private static Microsoft.Extensions.Configuration.IConfiguration configuration;
        public static void InitForCore(Microsoft.Extensions.Configuration.IConfiguration config)
        {
            configuration = config;
        }
#endif
#if NETSTANDARD || NETSTANDARD2_0
        public static string GetAppSettings(string keyName)
        {
            var jsonKeyName = "AppSettings:" + keyName;
            string keyValue = configuration[jsonKeyName];
            return keyValue;
        }
#endif
#if !NETSTANDARD && !NETSTANDARD2_0
        public static string GetAppSettings(string keyName)
        {
            var keyValue = ConfigurationManager.AppSettings[keyName];
            return keyValue;
        }
    }
#endif

    }`

**Comment by JasonBock** [comment] 2017-12-01 14:03
@JohnWigger having an abstraction like this for configuration is a good idea. I also think that all of the properties on `ApplicationContext` should be settable from code as well. Maybe in the static ctor `ApplicationContext` reads from configuration and sets all the values, and then after that the properties just get and set from private static fields. A developer can choose to set them after this initial configuration is done.

Ultimately @rockfordlhotka will decide :)

**Comment by rockfordlhotka** [comment] 2017-12-07 21:30
This is actually a duplicate of #525 - or at least they are the same basic issue/problem.

**Closed** 2017-12-07 21:30 UTC
Labels: duplicate, enhancement
