### ISSUE TITLE
[Idea] AddCsla() - configure context managers

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/csla#1124] opened 2019-04-08 11:10 UTC
**Is your feature request related to a problem? Please describe.**
When calling `AddCsla()` :  https://github.com/MarimerLLC/csla/blob/594978d2acf3b6be490ab3a89c0f8653ac9dda28/Source/Csla.Shared/Configuration/ConfigurationExtensions.cs#L26

This currently returns a csla flavoured builder.

I'd also like to configure the "ContextManager"s that should be used for the application so that my CSLA configuration experience is all in one place.

```
services.AddCsla().AddContextManager<MyFancyWebContextManager>()
```

At the moment, CSLA has static properties to set these context managers on `ApplicationContext.`

However I would prefer to use DI so something like the following, to possibly register multiple context managers.

```
            services.AddSingleton<IContextManager>(sp =>
            {
                return new HttpContextAccessorContextMananger(sp); 
            });

            services.AddSingleton<IContextManager>(sp =>
            {
                return new ApplicationContextManager();
            });

```

One problem here is that there are different context managers, one for web scenario and one for non web scenario. Assumedly somewhere, is some logic where CSLA decides which one it needs to use. Perhaps this logic could be pulled out and registered as a factory in the DI container, i.e:

```
            // register the available IContextManager's first..
          services.AddSingleton<IContextManager>(sp =>
            {
                return new HttpContextAccessorContextMananger(sp); 
            });

            services.AddSingleton<IContextManager>(sp =>
            {
                return new ApplicationContextManager();
            });

           // Register the factory - that decides which one to return..
            services.AddScoped<IContextManagerFactory>(sp =>
            {
                var allContextManagers = sp.GetServices<IContextManager>();
                foreach (var item in allContextManagers)
                {
                    if(item.IsValid)
                    {
                        return item;
                    }
                }
            });

```

The end goal would be that all CSLA code that iteracts with `IContextManager` would now resolve it via the `IContextManagerFactory`. If this was in static code, it could locate the factory from some static property containing the current IServiceProvider (which CSLA can grab a reference to, at application startup level, and during http request via a middleware at start of request). This one static property for "IServiceProvider" could negate the need for the many static properties present today (for things like context managers and other configuration / extension points.

**Comment by rockfordlhotka** [comment] 2019-04-08 20:48
I think this is a duplicate of #1068?

Though you've provided some great detail here that's quite useful!

**Comment by dazinator** [comment] 2019-04-08 22:25
Ah right yes. Feel free to close and can just leave this issue linked if that's what you prefer!

**Closed** 2019-04-09 04:59 UTC
