### ISSUE TITLE
Please upgrade your samples. The current ones are creating a ton of errors

### ISSUE THREAD

**Issue by Tony20221** [MarimerLLC/csla#3058] opened 2022-08-13 18:42 UTC
I selected the ProjectTracker to check out CSLA and the app didn't compile and there were a lot of errors. It's referencing CSLA 5.4 which seems to not exist so I removed all references to it and had the package manager install version 6.1 in the different projects. I removed all non WinForms UI projects to lessen my work. After trying to clean up everything I still ended up with many errors. This screen capture shows some.
I wish the CSLA maintainers would upgrade the samples to the current one. It's frustrating for us developers who want to check out the library to find these errors and nothing works. I don't get a good impression about a repo when I notice these kinds of outdated projects. Some of us go straight the demo apps to see the capability of some software.

![image](https://user-images.githubusercontent.com/99626433/184506725-ac06cecb-5843-4341-a1f8-bb2b1f6afdf6.png)

**Comment by rockfordlhotka** [comment] 2022-08-15 19:23
Thank you for the input. This is a duplicate of https://github.com/MarimerLLC/csla/issues/2551

**Closed by rockfordlhotka** 2022-08-15 19:23 UTC
