### ISSUE TITLE
SingleCriteria and Warning CSLA0010 Operation argument types should be serializable.

### ISSUE THREAD

**Issue by michaelcsikos** [MarimerLLC/csla#660] opened 2016-11-01 00:32 UTC
This warning is showing for `DataPortal_XYZ(SingleCriteria<C> criteria)` method declarations.

Should the `SingleCriteria<C>` and `SingleCriteria<B, C>` classes be decorated as `[Serializable]`?

**Comment by rockfordlhotka** [comment] 2016-11-10 18:25
Duplicate of #623

**Closed by rockfordlhotka** 2016-11-10 18:25 UTC
Labels: duplicate
